DROP TABLE IF EXISTS VersionRaw;
DROP TABLE IF EXISTS VersionMix;
DROP TABLE IF EXISTS VersionMaster;
DROP TABLE IF EXISTS Collaborator;
DROP TABLE IF EXISTS Projet;
DROP TABLE IF EXISTS Utilisateur;
DROP TABLE IF EXISTS Discussion;
